# copyright ############################### #
# This file is part of the Xcoll package.   #
# Copyright (c) CERN, 2026.                 #
# ######################################### #

import numpy as np

import xobjects as xo
import xtrack as xt

from ..general import _pkg_root


BEAMGAS_PROCESSES = ('brems', 'coulomb')


def _resolve_process(process):
    """
    Validate and normalise the name of a beam-gas process.

    Parameters
    ----------
    process : str
        Name of the process, ``'brems'`` or ``'coulomb'``.

    Returns
    -------
    process : str
        Normalised process name.
    """
    if isinstance(process, str):
        process = process.lower()
        if process in BEAMGAS_PROCESSES:
            return process
        if process in ('bremsstrahlung', 'bremss'):
            return 'brems'

    raise ValueError(
        "`process` must be either 'brems' (bremsstrahlung) or 'coulomb' "
        f"(Coulomb scattering). Got {process!r} instead.")


def _resolve_n_scattering_events(*, n_scattering_events, default):
    """
    Validate the requested number of Monte Carlo scattering events.

    Parameters
    ----------
    n_scattering_events : int or None
        Requested number of events.
    default : int or None
        Value used when ``n_scattering_events`` is ``None``.

    Returns
    -------
    n_scattering_events : int
        Validated number of events.
    """
    if n_scattering_events is None:
        n_scattering_events = default

    if n_scattering_events is None:
        raise ValueError("`n_scattering_events` is required.")

    if n_scattering_events < 0:
        raise ValueError("`n_scattering_events` must be non-negative.")

    return int(n_scattering_events)


class BeamGasScattering(xt.BeamElement):
    """
    Beam element that generates beam-residual-gas interactions at one location.

    Each element represents one beam-gas scattering centre, standing for the
    section of lattice that precedes it (up to the previous scattering centre,
    or the start of the line for the first one). When :meth:`scatter` is called
    it draws macro-particles from the local matched Gaussian distribution,
    makes each of them interact once with the residual gas, and returns a
    weighted particle sample. The weights are normalised such that their sum
    is the beam-gas interaction rate [1/s] produced by the represented lattice
    section, so that tracking the sample and summing the weight of the lost
    particles directly gives the beam-gas loss rate.

    The element is *passive* during normal tracking (its track kernel is a
    no-op); all the physics happens inside :meth:`scatter`.

    Local optics, beam parameters and gas densities are normally supplied by
    :class:`xcoll.BeamGasStudy`; direct construction is used to place the
    scattering centres in a line before configuring a study.

    Parameters
    ----------
    s : float, optional
        Longitudinal position of the element in the lattice [m]. Default 0.
    ds : float, optional
        Length of the lattice section represented by this element [m].
    particle_ref : xtrack.Particles, optional
        Reference particle.
    element_index : int, optional
        Index of this element in the line.
    alfx, betx : float, optional
        Horizontal Twiss parameters at the element.
    alfy, bety : float, optional
        Vertical Twiss parameters at the element.
    dx, dpx : float, optional
        Horizontal dispersion and its derivative at the element.
    dy, dpy : float, optional
        Vertical dispersion and its derivative at the element.
    x_co, px_co : float, optional
        Horizontal closed-orbit position and normalised momentum.
    y_co, py_co : float, optional
        Vertical closed-orbit position and normalised momentum.
    zeta_co, delta_co : float, optional
        Longitudinal closed-orbit coordinate and relative momentum deviation.
    gemitt_x, gemitt_y : float, optional
        Horizontal and vertical geometric emittances [m rad].
    sigma_z : float, optional
        RMS bunch length [m].
    sigma_delta : float, optional
        RMS relative momentum spread.
    n_scattering_events : int, optional
        Number of beam-gas interactions generated by this element.
    interaction_rate : float, optional
        Beam-gas interaction rate produced by the represented lattice section
        [1/s]. Set by :meth:`xcoll.BeamGasStudy.initialise_beamgas`; it is the
        total weight distributed over the generated macro-particles.
    process : {'brems', 'coulomb'}, optional
        Beam-gas process generated by this element.
    atomic_densities : dict, optional
        Mapping ``{element_symbol: atomic_density}`` of the local gas
        composition [atoms/m^3].

    Attributes
    ----------
    s : float
        Longitudinal position of the element [m].
    ds : float
        Length of the represented lattice section [m].
    interaction_rate : float
        Beam-gas interaction rate of the represented section [1/s].
    atomic_densities : dict
        Local gas composition [atoms/m^3].
    mean_free_path : float
        Local beam-gas mean free path [m], restricted to the generated part of
        the cross section.
    scatter_log : dict or None
        Per-event record of the last call to :meth:`scatter`, as a mapping of
        column name to array: ``particle_id``, ``gas``, ``theta``,
        ``photon_energy`` and ``weight``. ``None`` before the first call.
        :meth:`xcoll.BeamGasStudy.interaction_log` collects these records from
        all the elements into a single :class:`xtrack.Table`.

    Notes
    -----
    **Physics summary**

    For each of the ``n_scattering_events`` generated macro-particles:

    1. Initial coordinates are drawn from the local matched Gaussian
       distribution, built from the Twiss parameters, the geometric
       emittances, ``sigma_z`` and ``sigma_delta``, and shifted onto the local
       closed orbit. Betatron and dispersive contributions are included;
       transverse coupling is not.
    2. A gas species is drawn with a probability proportional to its
       contribution ``n_gas * sigma_gas`` to the local interaction rate.
    3. One interaction of the configured ``process`` is applied, using the
       cross-section models of :mod:`xcoll.beamgas.cross_sections`.
    4. The macro-particle is given a weight
       ``interaction_rate/n_scattering_events`` times the importance weight of
       the sampled event, so that the total weight of the sample is the
       section interaction rate [1/s].

    Every generated macro-particle interacts exactly once. This *forced
    interaction* scheme is the correct estimator in the single-scattering
    regime of a dilute residual gas, where the real probability of
    interacting in one turn is many orders of magnitude below one.
    """

    _xofields = {
        'p0c': xo.Float64,
        'ds': xo.Float64,
        'interaction_rate': xo.Float64,
        'n_scattering_events': xo.Int64,
        'gemitt_x': xo.Float64,
        'gemitt_y': xo.Float64,
        'alfx': xo.Float64,
        'betx': xo.Float64,
        'alfy': xo.Float64,
        'bety': xo.Float64,
        'dx': xo.Float64,
        'dpx': xo.Float64,
        'dy': xo.Float64,
        'dpy': xo.Float64,
        'sigma_z': xo.Float64,
        'sigma_delta': xo.Float64,
    }

    isthick = False
    behaves_like_drift = False
    allow_track = True
    skip_in_loss_location_refinement = True

    _extra_c_sources = [
        _pkg_root.joinpath('beam_elements', 'elements_src', 'beamgas.h')
    ]

    def __init__(self, s=0.0, ds=0.0,
                 particle_ref=None,
                 element_index=0,
                 alfx=0.0, betx=0.0, alfy=0.0, bety=0.0,
                 dx=0.0, dpx=0.0, dy=0.0, dpy=0.0,
                 x_co=0.0, px_co=0.0, y_co=0.0, py_co=0.0,
                 zeta_co=0.0, delta_co=0.0,
                 gemitt_x=0.0, gemitt_y=0.0,
                 sigma_z=0.0, sigma_delta=0.0,
                 n_scattering_events=None,
                 interaction_rate=0.0,
                 process='brems',
                 atomic_densities=None,
                 **kwargs):
        """
        Create a beam-gas scattering element.

        Parameters
        ----------
        See the class docstring.

        Returns
        -------
        None
        """
        if '_xobject' in kwargs.keys():
            self.xoinitialize(**kwargs)
            return

        super().__init__(**kwargs)

        if particle_ref is None:
            particle_ref = xt.Particles(_context=self._buffer.context)

        self.s = s
        self.ds = ds
        self.particle_ref = particle_ref
        self.element_index = element_index
        self.alfx = alfx
        self.betx = betx
        self.alfy = alfy
        self.bety = bety
        self.dx = dx
        self.dpx = dpx
        self.dy = dy
        self.dpy = dpy
        self.x_co = x_co
        self.px_co = px_co
        self.y_co = y_co
        self.py_co = py_co
        self.zeta_co = zeta_co
        self.delta_co = delta_co
        self.gemitt_x = gemitt_x
        self.gemitt_y = gemitt_y
        self.sigma_z = sigma_z
        self.sigma_delta = sigma_delta
        self.n_scattering_events = _resolve_n_scattering_events(
            n_scattering_events=n_scattering_events, default=0)
        self.interaction_rate = interaction_rate
        self.process = process
        self.atomic_densities = {} if atomic_densities is None \
            else dict(atomic_densities)

        # Filled in by BeamGasStudy.initialise_beamgas()
        self._calculators = {}
        self._xsecs = {}
        self.scatter_log = None

    @property
    def process(self):
        """
        Beam-gas process generated by this element.

        Parameters
        ----------
        None

        Returns
        -------
        process : {'brems', 'coulomb'}
            Name of the configured process.
        """
        return self._process

    @process.setter
    def process(self, value):
        """
        Set the beam-gas process generated by this element.

        Parameters
        ----------
        value : {'brems', 'coulomb'}
            Name of the process.

        Returns
        -------
        None
        """
        self._process = _resolve_process(value)

    @property
    def gas_species(self):
        """
        Gas species present at this element.

        Parameters
        ----------
        None

        Returns
        -------
        species : list of str
            Chemical symbols of the local gas species, in a fixed order.
        """
        return list(self.atomic_densities.keys())

    @property
    def interaction_probabilities(self):
        """
        Relative contribution of each species to the local interaction rate.

        Parameters
        ----------
        None

        Returns
        -------
        probabilities : ndarray
            Probability that an interaction occurs on each of the species
            listed by :attr:`gas_species`. The array sums to one.
        """
        self._check_initialised()
        contributions = np.array(
            [self.atomic_densities[kk]*self._xsecs[kk]
             for kk in self.gas_species],
            dtype=float)
        total = contributions.sum()
        if total <= 0.0:
            raise ValueError(
                f"No beam-gas interactions possible at element "
                f"'{getattr(self, 'name', '?')}': all gas densities are zero.")

        return contributions/total

    @property
    def mean_free_path(self):
        """
        Local beam-gas mean free path.

        Parameters
        ----------
        None

        Returns
        -------
        mean_free_path : float
            Mean free path [m] against the generated part of the beam-gas
            cross section, i.e. restricted to the configured photon-energy or
            scattering-angle range.
        """
        self._check_initialised()
        inverse = sum(self.atomic_densities[kk]*self._xsecs[kk]
                      for kk in self.gas_species)

        return np.inf if inverse <= 0.0 else 1.0/inverse

    def _configure(self, **kwargs):
        """
        Set the element parameters supplied by :class:`xcoll.BeamGasStudy`.

        Parameters
        ----------
        **kwargs
            Any of the constructor parameters, plus the private
            ``_calculators`` and ``_xsecs`` mappings holding the shared
            cross-section models and total cross sections per gas species.

        Returns
        -------
        None
        """
        config_allowed = {
            's', 'ds', 'particle_ref', 'element_index',
            'alfx', 'betx', 'alfy', 'bety',
            'dx', 'dpx', 'dy', 'dpy',
            'x_co', 'px_co', 'y_co', 'py_co',
            'zeta_co', 'delta_co',
            'gemitt_x', 'gemitt_y',
            'sigma_z', 'sigma_delta',
            'n_scattering_events', 'interaction_rate',
            'process', 'atomic_densities',
            '_calculators', '_xsecs',
        }

        unknown = set(kwargs) - config_allowed
        if unknown:
            bad = ", ".join(sorted(unknown))
            raise KeyError(f"Unsupported configure() keys: {bad}")

        n_scattering_events = kwargs.pop('n_scattering_events', None)
        if n_scattering_events is not None:
            self.n_scattering_events = _resolve_n_scattering_events(
                n_scattering_events=n_scattering_events,
                default=self.n_scattering_events)

        for kk, vv in kwargs.items():
            setattr(self, kk, vv)
            if kk == 'particle_ref':
                self.p0c = self.particle_ref.p0c[0]

    def _check_initialised(self):
        """
        Raise if the element has not been configured by a study yet.

        Parameters
        ----------
        None

        Returns
        -------
        None
        """
        if not self._calculators or not self.atomic_densities:
            raise ValueError(
                f"Element '{getattr(self, 'name', '?')}' has not been "
                f"initialised. Call BeamGasStudy.initialise_beamgas() first.")

    def _generate_primaries(self, n, rng):
        """
        Draw macro-particles from the local matched Gaussian distribution.

        Betatron and dispersive contributions are generated relative to the
        closed orbit, which is then added so that the returned coordinates are
        the physical ones. The interaction is applied afterwards, on the
        physical momentum direction of each macro-particle.

        Parameters
        ----------
        n : int
            Number of macro-particles to generate.
        rng : numpy.random.Generator
            Random number generator.

        Returns
        -------
        x, px, y, py, zeta, delta : ndarray
            Physical coordinates of the generated macro-particles.
        """
        u = rng.standard_normal((6, n))

        delta = self.sigma_delta*u[5]
        zeta = self.sigma_z*u[4]

        x = np.sqrt(self.gemitt_x*self.betx)*u[0] + self.dx*delta
        px = (np.sqrt(self.gemitt_x/self.betx)*(u[1] - self.alfx*u[0])
              + self.dpx*delta)
        y = np.sqrt(self.gemitt_y*self.bety)*u[2] + self.dy*delta
        py = (np.sqrt(self.gemitt_y/self.bety)*(u[3] - self.alfy*u[2])
              + self.dpy*delta)

        return (x + self.x_co, px + self.px_co,
                y + self.y_co, py + self.py_co,
                zeta + self.zeta_co, delta + self.delta_co)

    def scatter(self, rng=None):
        """
        Generate weighted beam-gas-scattered macro-particles.

        Parameters
        ----------
        rng : numpy.random.Generator or None, optional
            Random number generator. If ``None``, a fresh unseeded generator
            is used.

        Returns
        -------
        particles : xtrack.Particles
            Macro-particles that have undergone one beam-gas interaction,
            weighted so that their total weight is the beam-gas interaction
            rate [1/s] of the lattice section represented by this element.
        """
        if rng is None:
            rng = np.random.default_rng()

        self._check_initialised()

        n = int(self.n_scattering_events)
        if n <= 0:
            raise ValueError(
                "`n_scattering_events` must be positive to generate "
                "beam-gas-scattered particles.")

        x, px, y, py, zeta, delta = self._generate_primaries(n, rng)

        # Assign a gas species to each event, proportionally to its
        # contribution to the local interaction rate
        species = self.gas_species
        i_species = rng.choice(
            len(species), size=n, p=self.interaction_probabilities)

        weight = np.empty(n)
        theta = np.empty(n)
        photon_energy = np.empty(n)
        # NOTE: an object array (and not a fixed-width unicode array) is used
        # on purpose: `xtrack.view.View`, which wraps the elements accessed
        # through `line[name]`, corrupts numpy unicode arrays on conversion.
        gas = np.empty(n, dtype=object)

        for ii, kk in enumerate(species):
            mask = i_species == ii
            if not mask.any():
                continue
            sample = self._calculators[kk].sample_deflections(
                px[mask], py[mask], delta[mask], rng)
            px[mask] = sample.px
            py[mask] = sample.py
            delta[mask] = sample.delta
            weight[mask] = sample.weight
            theta[mask] = sample.theta
            photon_energy[mask] = sample.photon_energy
            gas[mask] = kk

        # Normalise the weights to the interaction rate of the section
        weight *= self.interaction_rate/n

        # Leave room for the secondaries that collimators may produce
        particles = xt.Particles(
            _capacity=4*n,
            p0c=self.p0c,
            mass0=self.particle_ref.mass0,
            q0=self.particle_ref.q0,
            pdg_id=self.particle_ref.pdg_id,
            x=x, px=px, y=y, py=py, zeta=zeta, delta=delta,
            weight=weight,
            s=self.s,
        )

        particles.at_element = self.element_index

        self.scatter_log = {
            'particle_id': particles.particle_id[:n].copy(),
            'gas': gas,
            'theta': theta,
            'photon_energy': photon_energy,
            'weight': weight,
        }

        return particles

    def track(self, particles):
        """
        Track particles through the element without applying a kick.

        Beam-gas interactions are generated explicitly by :meth:`scatter`;
        during normal lattice tracking this element is a passive marker.

        Parameters
        ----------
        particles : xtrack.Particles
            Particles tracked through the passive marker element.

        Returns
        -------
        None
        """
        super().track(particles)
