def scatter(*, npart, x_particles, xp_particles, y_particles, yp_particles, s_particles, p_particles, part_hit,
                part_abs, part_impact, part_indiv, part_linteract, nhit_stage, nabs_type,
                linside, run_exenergy, run_anuc, run_zatom, run_emr, run_rho,  run_hcut, run_bnref, run_csref0, run_csref1, run_csref4, run_csref5,
                run_radl, run_dlri, run_dlyi, run_eum, run_ai, run_collnt, run_cprob, run_xintl, run_bn, run_ecmsq, run_xln15s,
                run_bpp, is_crystal, c_length, c_rotation, c_aperture, c_offset, c_tilt, c_enom, onesided, random_generator_seed
                ):
    try:
        import xcoll.beam_elements.pyk2 as pyk2
    except ImportError:
        raise Exception("Error: Failed importing pyK2 (did you compile?). Cannot track.")

    pyk2.initialise_random(num_particles=npart, random_generator_seed=random_generator_seed)

    pyk2.pyk2_run(num_particles=npart,
                x_particles=x_particles,
                xp_particles=xp_particles,
                y_particles=y_particles,
                yp_particles=yp_particles,
                s_particles=s_particles,
                p_particles=p_particles,
                part_hit=part_hit,
                part_abs=part_abs,
                part_impact=part_impact,
                part_indiv=part_indiv,
                part_linteract=part_linteract,
                nhit_stage=nhit_stage,
                nabs_type=nabs_type,
                linside=linside,
                run_exenergy=run_exenergy,
                run_anuc=run_anuc,
                run_zatom=run_zatom,
                run_emr=run_emr,
                run_rho=run_rho,
                run_hcut=run_hcut,
                run_bnref=run_bnref,
                run_csref0=run_csref0,
                run_csref1=run_csref1,
                run_csref4=run_csref4,
                run_csref5=run_csref5,
                run_radl=run_radl,
                run_dlri=run_dlri,
                run_dlyi=run_dlyi,
                run_eum=run_eum,
                run_ai=run_ai,
                run_collnt=run_collnt,
                run_cprob=run_cprob,
                run_xintl=run_xintl,
                run_bn=run_bn,
                run_ecmsq=run_ecmsq,
                run_xln15s=run_xln15s,
                run_bpp=run_bpp,
                is_crystal=is_crystal,
                c_length=c_length,
                c_rotation=c_rotation,
                c_aperture=c_aperture,
                c_offset=c_offset,
                c_tilt=c_tilt,
                c_enom=c_enom,
                onesided=onesided,
                )